// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.14;

/**
 * @notice This file will be auto-generated by snarkjs
 * 
 * To generate this file, run:
 *   snarkjs zkey export solidityverifier part3_final.zkey VerifierPart3.sol
 * 
 * This verifier expects:
 *   - Proof: (a[2], b[2][2], c[2])
 *   - Public signals: uint[] with 84 elements
 */
contract VerifierPart3 {
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool) {
        // This will be replaced by snarkjs generated code
        revert("VerifierPart3: Please generate this file using snarkjs zkey export solidityverifier");
    }
}


